AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB stack for Memo App

Resources:
  MemoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MemoTable
      # アクセスされた分だけ課金する設定
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: memoId
          AttributeType: S
      KeySchema:
        # パーティションキー設定
        - AttributeName: userId
          KeyType: HASH
        # userIdの中で並び替えるキー設定
        - AttributeName: memoId
          KeyType: RANGE
      # 暗号化設定
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: MemoApp

Outputs:
  # lambdaスタックがテーブル名参照するため
  MemoTableName:
    Description: DynamoDB table name
    Value: !Ref MemoTable
    Export:
      Name: MemoTableName

  # lambdaスタックがARN参照するため
  MemoTableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt MemoTable.Arn
    Export:
      Name: MemoTableArn